// Package llm provides a unified LLM functionality interface
//
// This package provides all LLM-related functionality, including:
//   - LLM client: Create and manage LLM client instances
//   - PR-related features: Generate PR content, summarize PR, reword PR, etc.
//   - Translation functionality: Translate text to English
//   - Language support: Multi-language prompt enhancement
//
// Usage example:
//
//	import (
//		infrastructurellm "github.com/zevwings/workflow/internal/infrastructure/llm"
//	)
//
//		// Use infrastructure layer convenience function to create PR LLM client (internally automatically creates config provider and LLM client)
//	prClient := infrastructurellm.NewPullRequestLLMClient()
//	content, err := prClient.GenerateContent("fix: bug", nil, "")
//	if err != nil {
//		// Handle error
//	}
package llm

import (
	"fmt"

	"github.com/zevwings/workflow/internal/llm/branch"
	"github.com/zevwings/workflow/internal/llm/client"
	"github.com/zevwings/workflow/internal/llm/pr"
)

// ============================================================================
// Interface Definitions
// ============================================================================

// LLMConfigProvider LLM configuration provider interface
//
// Used to get LLM provider configuration and language configuration from external configuration sources.
// Types implementing this interface can get configuration from config.LLMConfig or other configuration sources.
//
// Types returned by interface methods:
//   - GetProviderConfig() returns *ProviderConfig (i.e., client.ProviderConfig)
//   - GetLanguage() returns *SupportedLanguage (i.e., client.SupportedLanguage)
//
// Usage example:
//
//	import infrastructurellm "github.com/zevwings/workflow/internal/infrastructure/llm"
//
//	// Method 1: Use infrastructure layer convenience function (recommended, simplest)
//	prClient := infrastructurellm.NewPullRequestLLMClient()
//
//	// Method 2: Create provider using adapter and pass it in
//	provider := infrastructurellm.NewLLMConfigProvider()
//	prClient := llm.NewPullRequestLLMClient(provider)
//
//	// Method 3: Manually implement LLMConfigProvider interface and pass it in
//	provider := yourCustomProvider // Implements LLMConfigProvider interface
//	prClient := llm.NewPullRequestLLMClient(provider)
type LLMConfigProvider interface {
	// GetProviderConfig gets provider configuration
	//
	// Returns:
	//   - *ProviderConfig: LLM provider configuration (APIKey, Model, URL)
	//   - error: Returns error if configuration is invalid
	GetProviderConfig() (*ProviderConfig, error)

	// GetLanguage gets language configuration
	//
	// Returns:
	//   - *SupportedLanguage: Language configuration, if nil means use default English configuration
	//   - error: Returns error if configuration is invalid
	GetLanguage() (*SupportedLanguage, error)
}

// ============================================================================
// Type Re-exports
// ============================================================================

// ProviderConfig provider configuration
//
// Basic configuration for LLM client, including API key, model name, and URL.
// This type is a type alias for client.ProviderConfig.
type ProviderConfig = client.ProviderConfig

// SupportedLanguage supported language information
//
// Language configuration for LLM prompt generation.
// This type is a type alias for client.SupportedLanguage.
type SupportedLanguage = client.SupportedLanguage

// LLMClient LLM client
//
// All LLM providers use the same client implementation, distinguished by configuration structs.
// This type is a type alias for client.LLMClient.
type LLMClient = client.LLMClient

// LLMRequestParams LLM request parameters
//
// Contains all parameters required to call LLM API.
// This type is a type alias for client.LLMRequestParams.
type LLMRequestParams = client.LLMRequestParams

// PullRequestContent PR content, including branch name, PR title, description, and scope
//
// Branch name, PR title, description, and scope generated by LLM, used to create Pull Request.
// This type is a type alias for pr.PullRequestContent.
type PullRequestContent = pr.PullRequestContent

// PullRequestReword PR Reword result, including title and description
//
// Title and full description generated by LLM based on current PR title and PR diff, used to update existing PR.
// This type is a type alias for pr.PullRequestReword.
type PullRequestReword = pr.PullRequestReword

// PullRequestSummary PR summary result, including summary document and file name
//
// PR summary document and corresponding file name generated by LLM.
// This type is a type alias for pr.PullRequestSummary.
type PullRequestSummary = pr.PullRequestSummary

// PullRequestLLMClient PR LLM client
//
// Encapsulates all PR-related LLM operations, including generating PR content, summarizing PR, rewording PR, and summarizing file changes.
// Provides unified interface and configuration management.
// This type is a type alias for pr.PullRequestLLMClient.
type PullRequestLLMClient = pr.PullRequestLLMClient

// BranchLLMClient branch LLM client
//
// Encapsulates all branch-related LLM operations, including translation functionality.
// Provides unified interface and configuration management.
// This type is a type alias for branch.BranchLLMClient.
type BranchLLMClient = branch.BranchLLMClient

// ============================================================================
// Internal Functions
// ============================================================================

// global gets global LLMClient singleton (internal function, not exported)
//
// Gets configuration from LLMConfigProvider interface, internally creates HTTP client and LLM client.
// Returns process-level LLMClient singleton, initialized on first call, subsequent calls reuse the same instance.
//
// Parameters:
//   - provider: LLM configuration provider (cannot be nil)
//
// Returns:
//   - LLMClient: LLM client instance
//   - error: Returns error if configuration is invalid or creation fails
func global(provider LLMConfigProvider) (LLMClient, error) {
	if provider == nil {
		return nil, fmt.Errorf("llm.global: LLMConfigProvider cannot be nil")
	}

	// Get provider configuration from interface
	providerConfig, err := provider.GetProviderConfig()
	if err != nil {
		return nil, fmt.Errorf("llm.global: failed to get LLM provider configuration: %w", err)
	}

	// Create global LLM client singleton (automatically uses http.Global())
	llmClient := client.Global(providerConfig)

	return llmClient, nil
}

// ============================================================================
// Public Constructors
// ============================================================================

// NewPullRequestLLMClient creates a new PR LLM client
//
// Gets configuration from LLMConfigProvider interface, internally automatically creates LLM client and HTTP client.
// Language configuration is obtained from provider, if nil then uses default English configuration.
// Returns process-level PullRequestLLMClient singleton, initialized on first call, subsequent calls reuse the same instance.
//
// Parameters:
//   - provider: LLM configuration provider (cannot be nil)
//
// Returns:
//   - *PullRequestLLMClient: PR LLM client instance
//
// Note:
//   - Function will panic if configuration is invalid
//   - LLM client and HTTP client are automatically created and managed internally
//   - Parameters passed on first call will be saved, subsequent calls will ignore parameters
//   - If nil is passed, will panic on first call
//
// Advantages:
//   - Reduce resource consumption: Avoid duplicate client instance creation
//   - Thread-safe: Can be safely used in multi-threaded environments
//   - Unified management: All PR LLM calls use the same client instance
//
// Usage example:
//
//	import infrastructurellm "github.com/zevwings/workflow/internal/infrastructure/llm"
//
//	// Method 1: Use infrastructure layer convenience function (recommended, simplest)
//	prClient := infrastructurellm.NewPullRequestLLMClient()
//	content, err := prClient.GenerateContent("fix: bug", nil, "")
//	summary, err := prClient.Summarize("PR Title", "PR Diff")
//
//	// Method 2: Create provider using adapter and pass it in
//	provider := infrastructurellm.NewLLMConfigProvider()
//	prClient := llm.NewPullRequestLLMClient(provider)
//
//	// Method 3: Manually implement LLMConfigProvider interface and pass it in
//	provider := yourCustomProvider // Implements LLMConfigProvider interface
//	prClient := llm.NewPullRequestLLMClient(provider)
func NewPullRequestLLMClient(provider LLMConfigProvider) *PullRequestLLMClient {
	if provider == nil {
		panic(fmt.Errorf("llm.NewPullRequestLLMClient: LLMConfigProvider cannot be nil"))
	}

	// Create LLM client
	llmClient, err := global(provider)
	if err != nil {
		panic(fmt.Errorf("llm.NewPullRequestLLMClient: failed to create LLM client: %w", err))
	}

	// Get language configuration
	lang, err := provider.GetLanguage()
	if err != nil {
		panic(fmt.Errorf("llm.NewPullRequestLLMClient: failed to get language configuration: %w", err))
	}

	// Use singleton function from PR package
	return pr.Global(llmClient, lang)
}

// NewBranchLLMClient creates a new branch LLM client
//
// Gets configuration from LLMConfigProvider interface, internally automatically creates LLM client and HTTP client.
// Returns process-level BranchLLMClient singleton, initialized on first call, subsequent calls reuse the same instance.
//
// Parameters:
//   - provider: LLM configuration provider (cannot be nil)
//
// Returns:
//   - *BranchLLMClient: Branch LLM client instance
//
// Note:
//   - Function will panic if configuration is invalid
//   - LLM client and HTTP client are automatically created and managed internally
//   - Parameters passed on first call will be saved, subsequent calls will ignore parameters
//   - If nil is passed, will panic on first call
//
// Advantages:
//   - Reduce resource consumption: Avoid duplicate client instance creation
//   - Thread-safe: Can be safely used in multi-threaded environments
//   - Unified management: All branch LLM calls use the same client instance
//
// Usage example:
//
//	import infrastructurellm "github.com/zevwings/workflow/internal/infrastructure/llm"
//
//	// Method 1: Use infrastructure layer convenience function (recommended, simplest)
//	branchClient := infrastructurellm.NewBranchLLMClient()
//	translated, err := branchClient.TranslateToEnglish("Hello")
//
//	// Method 2: Create provider using adapter and pass it in
//	provider := infrastructurellm.NewLLMConfigProvider()
//	branchClient := llm.NewBranchLLMClient(provider)
//
//	// Method 3: Manually implement LLMConfigProvider interface and pass it in
//	provider := yourCustomProvider // Implements LLMConfigProvider interface
//	branchClient := llm.NewBranchLLMClient(provider)
func NewBranchLLMClient(provider LLMConfigProvider) *BranchLLMClient {
	if provider == nil {
		panic(fmt.Errorf("llm.NewBranchLLMClient: LLMConfigProvider cannot be nil"))
	}

	// Create LLM client
	llmClient, err := global(provider)
	if err != nil {
		panic(fmt.Errorf("llm.NewBranchLLMClient: failed to create LLM client: %w", err))
	}

	// Use singleton function from branch package
	return branch.Global(llmClient)
}
